# services:
#   mongo:
#     build:
#       context: ./mongo-rs
#       args:
#         MONGO_VERSION: 6.0
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: mongo
#       MONGO_INITDB_ROOT_PASSWORD: example
#       MONGO_INITDB_DATABASE: mongo
#       MONGO_REPLICA_HOST: localhost
#       MONGO_REPLICA_PORT: 27017
#     ports:
#       - '27017:27017'
#   backend:
#     build: .
#     container_name: udpBackend
#     restart: unless-stopped
#     ports:
#       - '3000:3000'
#     environment:
#       DATABASE_URL: mongodb://mongo:example@mongo:27017/mongo?authSource=admin&replicaSet=rs0
#     depends_on:
#       - mongo

# volumes:
#   mongo-data: